name: Build and publish package

on: [push, pull_request, workflow_dispatch]

# Set permissions at the job level.
permissions: {}

jobs:
  package:
    runs-on: ubuntu-latest
    # Required by attest-build-provenance-github.
    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Build and Check Package
      uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516
      with:
        attest-build-provenance-github: 'true'

  pypi-publish:
    name: Upload release to PyPI
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [package]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pytest-sigil
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Download built packages
      uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
